### ISSUE TITLE
建议提交整个文件夹而非压缩包

### ISSUE THREAD

**Issue by Aether-254** [Emperor-Yan/ui_substitution#1]
建议提交整个文件夹而非压缩包，您可以将压缩包上传到 Releases。

**Comment by Emperor-Yan** [comment]
感谢issue~，但是提交文件夹的话会提示一次最多上次100个文件xwx
咱能问问有办法处理嘛

**Comment by 73410** [comment]
可以下一个github客户端，然后用客户端把库克隆到本地。然后把文件放到本地的文件夹，在客户端里提交代码

**Comment by 73410** [comment]
> 感谢issue~，但是提交文件夹的话会提示一次最多上次100个文件xwx 咱能问问有办法处理嘛

可以下一个github客户端，然后用客户端把库克隆到本地。然后把文件放到本地的文件夹，在客户端里提交代码

**Comment by Aether-254** [comment]
#2 已解决这个问题，麻烦作者合并一下谢谢
